version: "3.3"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3000"
    volumes:
      - "/work-hours-app/node_modules"
      - "./:/work-hours-app"
